# wrangler.toml
name = "cfw-backend-testapp"
main = "src/index.js"
compatibility_date = "2025-04-13"

[build]
command = "npm install"

[vars]
CF_APP_NAME = "cfw-backend-testapp"
COMPLEX_ENV_VAR = { key1 = "value1", key2 = "value2", num1 = 12345, boolVal1 = true }
